In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

**1**. Load a prebuilt dataset.
**2**. Build a neural network machine learning model that classifies images.
**3**. Train this neural network.
**4**. Evaluate the accuracy of the model.

In [10]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.16.2


# Load a dataset

Load and prepare the MNIST dataset. The pixel values of the images range from 0 through 255. Scale these values to a range of 0 to 1 by dividing the values by 255.0. This also converts the sample data from integers to floating-point numbers:

In [ ]:
mnist = tf.keras.datasets.mnist

In [12]:
print(mnist)

<module 'keras.datasets.mnist' from '/Users/mariiasv/Documents/Project/junior-ds-prep/.venv/lib/python3.12/site-packages/keras/datasets/mnist/__init__.py'>


In [13]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [14]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [15]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [16]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

# Build a machine learning model

In [17]:

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])
  

/Users/mariiasv/Documents/Project/junior-ds-prep/.venv/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
2025-05-04 19:05:02.862566: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Pro
2025-05-04 19:05:02.862639: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2025-05-04 19:05:02.862643: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2025-05-04 19:05:02.862671: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-05-04 19:05:02.862690: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created Ten

# Train this neural network

In [18]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.18037069,  0.00947249, -0.08583349, -0.9230613 , -0.23231299,
        -0.32493386,  0.3234434 ,  0.23963852, -0.38783818, -0.7194687 ]],
      dtype=float32)

In [19]:
tf.nn.softmax(predictions).numpy()

array([[0.13524185, 0.11399636, 0.10363348, 0.04486386, 0.08951274,
        0.08159435, 0.1560439 , 0.14349963, 0.07661982, 0.05499406]],
      dtype=float32)

In [20]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [21]:
loss_fn(y_train[:1], predictions).numpy()

2.505995

In [22]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

# Train and evaluate your model

In [23]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2025-05-04 19:05:33.219198: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.8335 - loss: 0.5530
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.8918 - loss: 0.3897
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.8887 - loss: 0.4025
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.8872 - loss: 0.4119
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.8851 - loss: 0.4258


In [25]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 4ms/step - accuracy: 0.9150 - loss: 0.3294


[0.32940417528152466, 0.9150000214576721]

In [26]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [27]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.1051019e-04, 4.9189766e-06, 1.2347417e-02, 6.1497563e-03,
        1.3733532e-04, 1.3220168e-03, 2.3527991e-06, 9.7852612e-01,
        2.8005519e-04, 3.1943680e-04],
       [9.7069726e-04, 9.7818468e-03, 9.5595318e-01, 9.2108417e-03,
        1.3722834e-05, 3.7650445e-03, 1.0575387e-02, 1.7925670e-07,
        9.7243795e-03, 4.7434874e-06],
       [4.1654079e-05, 9.2520154e-01, 8.8761392e-04, 9.8895172e-05,
        8.8239415e-03, 1.1098901e-04, 3.4751670e-04, 6.1319213e-02,
        1.0639401e-04, 3.0623104e-03],
       [4.7041258e-01, 7.2856732e-05, 5.6190579e-04, 8.6872060e-05,
        1.5733741e-02, 2.5596928e-03, 6.3791052e-03, 4.9554747e-01,
        3.7212879e-04, 8.2735233e-03],
       [7.2102584e-06, 3.1470131e-07, 3.9954471e-06, 3.0805322e-07,
        9.9067605e-01, 1.0945297e-05, 3.4486479e-06, 2.9911669e-03,
        2.1395752e-05, 6.2851445e-03]], dtype=float32)>